CREATE TABLE USER(
	ID_USER INTEGER NOT NULL,
	STR_NAME VARCHAR(255) NOT NULL,
	STR_EMAIL VARCHAR(255) NOT NULL,
	STR_LOGIN VARCHAR(255) NOT NULL,
	STR_PASS VARCHAR(255) NOT NULL,
	BOOL_COORDINATOR BOOLEAN NOT NULL,
	BOOL_ADMIN BOOLEAN NOT NULL,
	CONSTRAINT PK_USR PRIMARY KEY (ID_USR)
);

CREATE TABLE DISCIPLINE(
	ID_DISCIPLINE INTEGER NOT NULL,
	STR_DESCRIPTION VARCHAR(255) NOT NULL,
	INT_PERIOD INTEGER NOT NULL,
	CONSTRAINT PK_DISCIPLINE PRIMARY KEY (ID_DISCIPLINE)
);

CREATE TABLE SUBJECT(
	ID_SUBJECT INTEGER NOT NULL,
	ID_DISCIPLINE INTEGER NOT NULL,
	ID_PARENT INTEGER,
	CONSTRAINT PK_SUBJECT PRIMARY KEY (ID_SUBJECT),
	CONSTRAINT FK_SUB_RF_DIS FOREIGN KEY (ID_DISCIPLINE) REFERENCES DISCIPLINE(ID_DISCIPLINE)
	CONSTRAINT FK_SUB_RF_SUB FOREIGN KEY (ID_PARENT) REFERENCES SUBJECT(ID_SUBJECT)
);

CREATE TABLE DISCIPLINE_SUBJECT(
	ID_DISCIPLINE INTEGER NOT NULL,
	ID_SUBJECT INTEGER NOT NULL,
	CONSTRAINT FK_DIS_SUB_RF_DIS FOREIGN KEY (ID_DISCIPLINE) REFERENCES DISCIPLINE(ID_DISCIPLINE),
	CONSTRAINT FK_DIS_SUB_RF_SUB FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECT(ID_SUBJECT)
);

CREATE TABLE STUDENT_CLASS(
	ID_STUDENT_CLASS INTEGER NOT NULL,
	STR_DESCRIPTION VARCHAR(255) NOT NULL,
	INT_PERIOD INTEGER NOT NULL,
	CONSTRAINT PK_STUDENT_CLASS PRIMARY KEY (ID_STUDENT_CLASS)
);


CREATE TABLE STUDENT(
	ID_STUDENT INTEGER NOT NULL,
	ID_STUDENT_CLASS INTEGER,
	STR_NAME VARCHAR(255),
	STR_STUDENT_ID VARCHAR(255) NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (ID_STUDENT),
	CONSTRAINT FK_STU_RF_STU_CLA FOREIGN KEY (ID_STUDENT_CLASS) REFERENCES STUDENT_CLASS(ID_STUDENT_CLASS)		
);

CREATE TABLE STUDENT_GRADE_SUBJECT(
	ID_STU_GRA_DIS INTEGER NOT NULL,
	ID_STUDENT INTEGER NOT NULL,
	DBL_GRADE DOUBLE NOT NULL,
	ID_SUBJECT INTEGER NOT NULL,
	DATE_GRADE DATE NOT NULL,
	CONSTRAINT PK_STU_GRA_DIS PRIMARY KEY (ID_STU_GRA_DIS),
	CONSTRAINT FK_STD_GRA_DIS_RF_STU FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT(ID_STUDENT),
	CONSTRAINT FK_STD_GRA_DIS_RF_SUB FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECT(ID_SUBJECT)
); 	
