INSERT INTO SIMPLE_LOM (STR_LOM_TITLE, STR_URL, STR_CATALOG, STR_CATALOG_ENTRY, INT_DIFFICULT_LEVEL) VALUES
          ('SAMPLE', 'host.com/sample', 'ISBN', '000000000-0', 1);
INSERT INTO STUDENT_CLASS (STR_DESCRIPTION, INT_PERIOD) VALUES
          ('SAMPLE CLASS', 101);
INSERT INTO STUDENT (ID_STUDENT_CLASS,STR_NAME, STR_STUDENT_ID) VALUES
          ((SELECT ID_STUDENT_CLASS FROM STUDENT_CLASS WHERE STR_DESCRIPTION = 'SAMPLE CLASS'), 'STUDENT', '20160001');
INSERT INTO TAG (STR_VALUE) VALUES ('SAMPLE TAG');
INSERT INTO RL_TAG_LOM (ID_LOM, ID_TAG) VALUES
          ((SELECT ID_LOM FROM SIMPLE_LOM WHERE STR_LOM_TITLE = 'SAMPLE'), (SELECT ID_TAG FROM TAG WHERE STR_VALUE = 'SAMPLE TAG'));
